Rails.application.config.assets.precompile += %w( jquery.raty.js )
Rails.application.config.assets.precompile += %w( jquery.raty.css )
Rails.application.config.assets.precompile += %w( jquery.lazyload.js )
Rails.application.config.assets.precompile += %w( forem.css )
Rails.application.config.assets.precompile += %w( forem.js )