# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8d88cfef069d5c402c8ca9d83ccaf0249f61129e16809470145e46a9ae74ea0bf7c5e7d9a564d12ec666538c9b0be0c08f86ee332c691559e99a60b0570eb6

test:
  secret_key_base: 308c3e94bd2d1cd2acd106d558b0a4300e0185c2929dca1693706ebde56b61d0a51595787799334dd924c4887dea1856823751b611b0fd327e8a791c521de3af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
